### ISSUE TITLE
NameError: name 'fcntl' is not defined When I run redial on windows 11

### ISSUE THREAD

**Issue by realWilliamChin** [taypo/redial#51]
**Describe the bug**
PS C:\Users\realf> redial
Traceback (most recent call last):
  File "c:\users\realf\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\realf\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\realf\AppData\Local\Programs\Python\Python38\Scripts\redial.exe\__main__.py", line 7, in <module>
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\redial\__main__.py", line 7, in main
    sys.exit(run())
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\redial\redial.py", line 153, in run
    app = RedialApplication()
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\redial\redial.py", line 38, in __init__
    screen = urwid.raw_display.Screen()
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined
PS C:\Users\realf> redial
Traceback (most recent call last):
  File "c:\users\realf\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\realf\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\realf\AppData\Local\Programs\Python\Python38\Scripts\redial.exe\__main__.py", line 7, in <module>
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\redial\__main__.py", line 7, in main
    sys.exit(run())
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\redial\redial.py", line 153, in run
    app = RedialApplication()
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\redial\redial.py", line 38, in __init__
    screen = urwid.raw_display.Screen()
  File "c:\users\realf\appdata\local\programs\python\python38\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined

**To Reproduce**
1. pip3 install redial
2. run redial command in powershell

**Screenshots**
![image](https://user-images.githubusercontent.com/75707569/128290949-6d130242-164e-4c62-ac74-22dca88e56b7.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 latest version
 - python version: 3.8.10
 - redial version: 0.8
 - urwid version: 2.1.2

**Comment by fatihbaltaci** [comment]
Hi, Windows is not supported but you can use WSL (Windows Subsystem for Linux) on Windows.

https://github.com/taypo/redial#platforms

**Comment by realWilliamChin** [comment]
> Hi, Windows is not supported but you can use WSL (Windows Subsystem for Linux) on Windows.
> 
> https://github.com/taypo/redial#platforms

Thank you very much. That detail escaped my notice. 😆

**Comment by realWilliamChin** [comment]
Do not support windows
